---

- name: Disable ssh password authentication
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication\ '
    line: 'PasswordAuthentication no'
  notify: 'restart_sshd'

- name: Disable agent forwarding
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AllowAgentForwarding\ '
    line: 'AllowAgentForwarding no'
  notify: 'restart_sshd'

- name: Disable KbdInteractiveAuthentication
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^KbdInteractiveAuthentication\ '
    line: 'KbdInteractiveAuthentication no'
  notify: 'restart_sshd'
